{% set version = "6.8" %}

package:
  name: texinfo
  version: {{ version }}

source:
  fn: texinfo-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/texinfo/texinfo-{{ version }}.tar.gz
  sha256: 8e09cf753ad1833695d2bac0f57dc3bd6bcbbfbf279450e1ba3bc2d7fb297d08

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - help2man
    - gettext
    - gawk
    - make
  host:
    - ncurses
    - libiconv  # [osx]
    - perl
  run:
    - perl

test:
  commands:
    - makeinfo -h

about:
  home: http://www.gnu.org/software/texinfo/
  license: GPL-2.0 and GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'The GNU Documentation System.'
  dev_url: https://git.savannah.gnu.org/cgit/texinfo.git
  doc_url: https://www.gnu.org/software/texinfo/manual/texinfo/texinfo.pdf

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
