travis:
  secure:
    BINSTAR_TOKEN: RnuhtW3S24e848WJrCxLgsRWzHxbjjAkOhOZjzTZ0xOLvyCYYN/3ZgHxMEqTbfG6NJgEFQLPor58uIf0DqCwi0SrwsJCe4j+SjcbtQD4S09u8PPaStyfu5r+1HnuqZdWf0n/mDPLTyCA+5IM5PBk0S4MwzN3vh6SLFbZ2wpEZ704r2zot0vqvTMx/Z120mqGrjO7lX5UFtJarWvcUkQLzZeUuNGcbGdZbCLC6R1+rnKQjmX40eZGfi+SxLqKWFMGXUNlzAVZB0yObB01zM12sGxcCH/Z+tPoGR+DY/7lV/Di6IMvZDHIL1lX0m/1/oPRls/tzpC4G+c3b/tJ+ofVDOxp/g5PJjudL/u4HP7V+RFqXAnIX6216aT/8TEvKqLnbPr8bYIwTvJYbvx0/wyxi3aV/G1VW8rQ8jivGpDhjivxcBgjDDgYg+cnrZSPgDnwoKBqbK6c994KVtpqcyJw9OkkPFex6QHpYcoYmMWayaTsuzsHw/jtv0JudaJA4v+2hJnxFoU67e97k0E5+e5R6FWdbwnzi12rtCAl8hbrCYzBwYFnUxj2+6C46oeu5MWfY3lUlwGSQv9PfCSRGcKnkjVGBhyKrp4Yc31EowDvKQI6Mv5wgiV4QEPo4o8nNtTXdIDVl6QMlGr85257LAOTbqUU6sbr4ZS7rQi9D4sWHBk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
